In [13]:
from numpy import *

In [14]:
import numpy as np

In [78]:
G = array([[0,1,2],[3,4,5],[6,7,8]])

G

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [21]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [22]:
np.sqrt(-1) == np.emath.sqrt(-1)

//anaconda/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


False

In [30]:
A = random.rand(1,30)

A

array([[ 0.1178489 ,  0.36458839,  0.02645159,  0.79472001,  0.77328189,
         0.96428924,  0.46407114,  0.43380851,  0.02680998,  0.7828265 ,
         0.91312115,  0.06066217,  0.30188767,  0.92409663,  0.00970068,
         0.89491664,  0.60173859,  0.81896093,  0.17489518,  0.98235282,
         0.58601886,  0.11973234,  0.36051914,  0.57651959,  0.66499875,
         0.12931587,  0.43115512,  0.79157178,  0.04538297,  0.39831896]])

In [34]:
size(A)

30

In [33]:
mean(A)

0.48448539910987903

In [55]:
B = random.rand(5,3)
B = matrix(B)

C = random.rand(3,2)
C = matrix(C)

print(B * C)

print(dot (B,C))

[[ 0.54020311  0.49489176]
 [ 0.46834298  0.81937196]
 [ 0.79928372  1.35885873]
 [ 0.40135265  1.01157399]
 [ 0.51926794  0.96696203]]
[[ 0.54020311  0.49489176]
 [ 0.46834298  0.81937196]
 [ 0.79928372  1.35885873]
 [ 0.40135265  1.01157399]
 [ 0.51926794  0.96696203]]


In [57]:
E = random.rand(10)
E

array([ 0.7845027 ,  0.65508854,  0.60027652,  0.8684271 ,  0.14556244,
        0.90294431,  0.33754626,  0.56069159,  0.78772759,  0.9937006 ])

In [60]:
sort(E)

array([ 0.14556244,  0.33754626,  0.56069159,  0.60027652,  0.65508854,
        0.7845027 ,  0.78772759,  0.8684271 ,  0.90294431,  0.9937006 ])

In [76]:
F = random.rand(100)
F = sort(F)

F[99] = 0

F

array([  5.17701153e-04,   2.75254112e-03,   1.31323173e-02,
         1.40421560e-02,   2.42800465e-02,   2.44836010e-02,
         2.74297818e-02,   3.17977425e-02,   3.49592096e-02,
         3.73397608e-02,   5.13146246e-02,   6.35081343e-02,
         6.64379315e-02,   6.80218046e-02,   7.21195471e-02,
         8.93245955e-02,   9.19969374e-02,   9.23867401e-02,
         1.19500986e-01,   1.28830212e-01,   1.33859085e-01,
         1.45368678e-01,   1.64858926e-01,   1.66398317e-01,
         1.69313146e-01,   1.69606931e-01,   2.00543522e-01,
         2.01860280e-01,   2.26643930e-01,   2.30280974e-01,
         2.51161467e-01,   2.59208204e-01,   2.70094021e-01,
         2.95008344e-01,   3.09348593e-01,   3.23582835e-01,
         3.37229961e-01,   3.80848433e-01,   3.85953557e-01,
         4.17186762e-01,   4.26242650e-01,   4.33279441e-01,
         4.34937117e-01,   4.36758200e-01,   4.69746412e-01,
         4.87426047e-01,   4.89159176e-01,   5.01833570e-01,
         5.08620230e-01,

In [100]:
AA = random.rand(3,3)

AA_inv = linalg.inv(AA)

IAA = dot(AA,AA_inv)

abs(np.round(IAA))

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])